### ISSUE TITLE
Who is responsible for table.grow?

### ISSUE THREAD

**Issue by wingo** [WebAssembly/reference-types#102]
The overview document mentions that the `table.grow` instruction from bulk operations will need to take an initarg.  However the bulk operations proposal does not include `table.grow`.  Where is this instruction's home? :)

**Comment by lars-t-hansen** [comment]
table.grow is introduced in this proposal, see Overview, "Language Extensions".

**Comment by rossberg** [comment]
Ah yes, but the bullet point that @wingo is referring to is out of date. I'll remove it.

**Comment by rossberg** [comment]
Done.
