### ISSUE TITLE
`table.fill` needs to bounds check before executing `table.set`?

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/reference-types#105]
I want to

1. confirm my understanding of `table.fill`'s intended semantics, and
2. double check my reading of `table.fill`'s spec text.

It is my understanding that the intention is that if any part of the table region to be filled is out of bounds, then a trap must be raised and _the in-bounds subset of the table's elements left unmodified_. This understanding is based on [this assertion](https://github.com/WebAssembly/reference-types/blob/401c8eb929d6ee4ec0e7d6c2963997d15324f0b4/test/core/table_fill.wast#L54) that checks that we see the old table element value after a partially out-of-bounds `table.fill`, and the spec interpreter also [does an eager bounds check](https://github.com/WebAssembly/reference-types/blob/401c8eb929d6ee4ec0e7d6c2963997d15324f0b4/interpreter/exec/eval.ml#L255). If my understanding of `table.fill`'s intended semantics is not correct, then that assertion and bounds check in the spec interpreter need to change.

If my understanding of `table.fill`'s intended semantics *is* correct, then I want to double check my reading of `table.fill`'s spec text. The bounds checking that raises the trap only happens _after_ `n` reaches `0` (step 12), which means that for a partially-in-bounds `table.fill`, the in-bounds subset of elements will be mutated via the nested `table.set`s *before* we get to the `n = 0` base case and the trap is raised (or more likely: we do an nested `table.set` that is out of bounds and raises a trap). This contradicts my understanding of the intended semantics, the assertion linked above, and the spec interpreter.

`memory.fill`, on the other hand, does the bounds check _before_ checking for its `n = 0` base case (steps 12 and 13), and does not suffer these issues with partially-in-bounds fills. I believe that `table.fill` should be changed to do this bounds check before checking for its `n = 0` base case as well.

**Comment by lars-t-hansen** [comment]
I believe your understanding of table.fill's semantics is correct: https://github.com/WebAssembly/bulk-memory-operations/pull/123

**Comment by binji** [comment]
Yes, it looks like the `memory.fill` instruction was [updated in November 2019](https://github.com/WebAssembly/bulk-memory-operations/pull/129), but `table.fill` never was (that part of the spec seems to be from April 2019).

**Comment by fitzgen** [comment]
Fix at https://github.com/WebAssembly/reference-types/pull/106
