### ISSUE TITLE
"refedtype" unnecessary

### ISSUE THREAD

**Issue by wingo** [WebAssembly/reference-types#121]
The text format defines a `refedtype` production; see https://webassembly.github.io/reference-types/core/text/types.html#text-refedtype.  It appears to be there simply to make "ref.null func" read better (not repeating the "ref" bit).  However it doesn't correspond to any other concept in the binary format, the validation, the execution, etc.  To my mind, better to remove it.

**Comment by rossberg** [comment]
This is for forward compatibility with the typed (function) references proposal, where this distinction becomes relevant and the category of refedtypes (*) is extended. In particular, `funcref` becomes a shorthand for `(ref null func)`.

(*) Renamed to `heaptype` in that proposal, I should probably backport that change.

**Comment by wingo** [comment]
Do I understand correctly then that `refedtype` is the same as `reftype` but with the `null?` bit?

**Comment by rossberg** [comment]
And potentially other pointer-side attributes in the future, for example, a `shared` bit for shared references. Or possibly things like `eq`, `readonly`, etc. We also have been talking about making `i31` an attribute.

**Comment by wingo** [comment]
thanks for the explanation!
