### ISSUE TITLE
Missing design rationals for type annotated select

### ISSUE THREAD

**Issue by dbezhetskov** [WebAssembly/reference-types#125]
After removing subtyping rules (https://github.com/WebAssembly/reference-types/pull/87) it is unclear for me why we need type annotated select?
Right now we can infer the result type of select in the same way as we do for untyped version.
Is it just for future when we are able to return multiple values from select?

**Comment by dbezhetskov** [comment]
It is also weird that we can't use ref-types in select without type annotations, it forces engines to add `vec(valtypes)` for each select instruction. It is ok since `select` is rare instruction but it is still small overhead.

**Comment by rossberg** [comment]
Subtyping has been deferred, but not dropped forever. The combination of subtyping on refs and allowing them as operands to unannotated `select` would always force us into computing lubs, which we want to avoid. So allowing it now would not be future-proof wrt the later addition of subtyping.

**Comment by dbezhetskov** [comment]
ah, I see, thanks for the clarification @rossberg .
