### ISSUE TITLE
There is no DefaultValue for anyfunc/funcref

### ISSUE THREAD

**Issue by dbezhetskov** [WebAssembly/reference-types#127]
There is no DefaultValue for anyfunc/funcref:
https://webassembly.github.io/reference-types/js-api/index.html#defaultvalue

But actually the chrome and firefox suppose that this is null,
for example when you construct a Table({ "element": "anyfunc", "initial": 1 }) and the second argument is missing, firefox and chome just initialize the table with nulls and don't throw any exceptions.

Should we add the missing case for DefaultValue?

**Comment by rossberg** [comment]
I think this is fixed by #128.
