### ISSUE TITLE
Constant Expressions constraint

### ISSUE THREAD

**Issue by lum1n0us** [WebAssembly/reference-types#134]
https://github.com/WebAssembly/reference-types/blob/063d34eda68108fac28d783beaf501c23e9e38d0/test/core/data.wast#L480

according to the *Specification*, it doesn't look like an *invalid one*. 

> Note: Currently, constant expressions occurring as initializers of globals are further constrained in that contained
global.get instructions are only allowed to refer to imported globals. This is enforced in the validation rule for
modules by constraining the context C accordingly.

may be it is
``` wast
(assert_invalid
   (module 
     (global (mut i32) (i32.const 7)
     (memory 1)
     (data (global.get 0))
   )
   "constant expression required"
)
```

**Comment by rossberg** [comment]
This is invalid because the constant expression is referring to a _mutable_ global. That's never legal.

**Comment by lum1n0us** [comment]
yeah, but I also notice there is no such description in either latest spec(https://webassembly.github.io/spec/core/index.html) or the spec of reference type(https://webassembly.github.io/reference-types/core/).

**Comment by rossberg** [comment]
It's in the definition of constant expressions: https://webassembly.github.io/spec/core/valid/instructions.html#constant-expressions

**Comment by lum1n0us** [comment]
I mean the restriction about mutable imported globals can not be used in constant expressions. It just said "contained global.get instructions are only allowed to refer to imported globals".
________________________________

**Comment by rossberg** [comment]
Please look at the section I just linked, it says that the type of a global used in a const expression must be const.

**Comment by lum1n0us** [comment]
OK, you got me. You are right. Thanks.
________________________________
