### ISSUE TITLE
[Support] Are mixed (`anyref`) tables still supported, and if so, how are they encoded?

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/reference-types#136]
IIUC, tables are now typed as `funcref`, `externref` or `anyref` (with `anyref` tables able to hold a mix of `funcref` and `externref` elements).

In other threads, I've seen people mention in passing that `anyref` has been removed, but I can't find any more information about that. The version of the spec included with this proposal [doesn't seem to even mention `anyref`][1].

Can we still have `anyref` tables? If so, where is this documented? I cannot find how the `anyref` type is encoded. When importing a table, the binary format requires the limits and reftype, and explains how to encode limits, but only provides encodings for the two proper reftypes (`funcref` as 𝟶𝚡𝟽𝟶 and `externref` as 𝟶𝚡𝟼𝙵). If an `anyref` table is imported, what would its type encode to?

Sorry for all the questions. I've searched everywhere I could think of.

[1]: https://webassembly.github.io/reference-types/core/search.html?q=anyref

**Comment by tlively** [comment]
Anyref is now introduced in the GC proposal, so the current spec does not support tables of both `funcref` and `externref`.

**Comment by 7ombie** [comment]
Hey, @tlively.

**EDIT**: *Sorry, I hadn't seen your other response when I wrote this.*

Thank you, but I cannot find anything in the GC Proposal either. I read the MVP and Post-MVP docs, the README, and searched the issues. There doesn't seem to be a modified spec. Could you point me to where this was discussed, please? Sorry to be a pain.

**Comment by 7ombie** [comment]
Sorry. Are you saying that there is currently no plan to allow mixed tables, or that that plan is part of the GC proposal?

**Comment by tlively** [comment]
FWIW, `anyref` is introduced here: https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#reference-types.
