### ISSUE TITLE
Can anyref and funcref be null?

### ISSUE THREAD

**Issue by lachlansneff** [WebAssembly/reference-types#21]
While the current proposal allows them to be null, wouldn't it be better to have a set of refs that can be null and a set of refs that cannot so that call_indrect on a func ref doesn't require a nullcheck, etc?

**Comment by rossberg** [comment]
Yes, null-free reference types are meant to be part of follow-up proposals introducing precise reference types (e.g. as currently sketched in the GC proposal). Anyref and funcref require runtime type checks anyway to do anything with them, so whether null is included as one more value of unexpected type doesn't make a big difference; in particular, call_indirect already has to deal with null today, in the disguise of an "uninitialised" table slot.
