### ISSUE TITLE
Are reference types intended to always stay on a single thread?

### ISSUE THREAD

**Issue by lachlansneff** [WebAssembly/reference-types#26]
Since tables and globals (as far as I can tell) are not shared in the current threading proposal, are reference-types (and eventual gc-types) intended to always stay in a single wasm instance?

**Comment by chicoxyzzy** [comment]
Reference types are basis for GC types and interaction with threads is one of [requirements](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md#requirements) for GC types

**Comment by titzer** [comment]
Agreed, we will eventually want to have references across threads. For the web embedding, however, it will not be possible initially, since tables and globals are not currently shared across web workers. The current thinking is to add a "shared" bit to both globals and tables which would indicate whether they would be duplicated or shared across threads, which would be supported in other embeddings of WASM.

**Comment by chicoxyzzy** [comment]
@rossberg will this remain true with presence [JS Typed Objects](https://github.com/tschneidereit/proposal-typed-objects/blob/master/explainer.md#value-types)?

**Comment by rossberg** [comment]
@chicoxyzzy, good question. The typed object proposal might potentially be enriched with a similar attribute for defining types, which may allow respective objects to be shared. But there are a number of subtle problems to solve, e.g., what to do with prototypes or type identity.

**Comment by titzer** [comment]
Typed objects will have null prototypes in JS, but there @rossberg is right. There are a number of subtleties here that I suspect will cause more problems for JS, so it is reasonable to expect they will lag behind "pure" wasm objects for sharing. Which reminds me of a V8 implementation gotcha here...ergh

**Comment by lukewagner** [comment]
> > Typed objects will have null prototypes in JS
> 
> @titzer, I'm afraid that's not what the TO proposal currently intends.

[As currently proposed](https://github.com/WebAssembly/gc/blob/2d8ee8d5d255e90c05a140fcfae2bb2643fcf059/proposals/gc/MVP-JS.md#typed-objects), type objects would have a null prototype when created from an *internal* type definition.  (See also the [examples](https://github.com/WebAssembly/gc/blob/2d8ee8d5d255e90c05a140fcfae2bb2643fcf059/proposals/gc/MVP-JS.md#examples) that show this difference.)  So I think the abovementioned shared-ness rules in the type system, combined with instantiation-time checks, could indeed prevent shared type objects pointing to (necessarily un-shared) JS objects via `__proto__`.

**Comment by rossberg** [comment]
I think this has been answered.
