### ISSUE TITLE
Bikeshedding: rename ref.func to func.ref

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/reference-types#30]
While working on the function references and GC proposals I noticed that some naming conventions become a bit arbitrary again. For example, for function references we currently have:

- `ref.func`
- `func.bind`
- `call_ref`

I'd like to make at least the first two more consistent by renaming `ref.func` to `func.ref`. The idea being that all instructions producing/consuming a particular class of reference have its prefix.

That might also suggest renaming `call_ref` to `func.call`, though that may be confusing with plain calls. Not sure we can do much about calls, that ship has probably sailed. Maybe `call` and `call_indirect` should have been `func.call` and `table.call`, but then what about `call_ref`?

**Comment by titzer** [comment]
> The idea being that all instructions producing/consuming a particular class of reference have its prefix.

That seems reasonable for instructions that are inherently tied to a particular class of reference.

For calls, I think I am OK with keeping `call_function` `return_call_function``call_indirect` `return_call_indirect`. What about `ref.call_function` and `ref.return_call_function`? It's a little redundant, but it would be a continuation from the current naming scheme consistent with the above idea of "kind/type as prefix".

**Comment by rossberg** [comment]
@titzer, well, the "kind/type prefix" in all other cases of ops going through references is the thing being referenced, esp in the GC proposal (struct.new, struct.get, array.set, ...). The only ops that have a ref prefix themselves are the ones that deal with a ref itself in a generic fashion (ref.is_null, ...). So ref.call_function would not quite fit into that scheme.

**Comment by titzer** [comment]
What about `funcref.call` then?

**Comment by rossberg** [comment]
That would imply naming all the struct ops `structref.get` etc.  But maybe something like `ref.func.call` and `ref.struct.get` makes sense? That might actually provide a naming scheme that scales to other future extensions, e.g., if we were to add first-class tableref's then we'd have `ref.table.get` which is different from `table.get`.

**Comment by titzer** [comment]
It's a mouthful, but `ref.func.call` sounds fine to me.

**Comment by binji** [comment]
In that case we'd keep `ref.func` instead of renaming to `func.ref`, right?

**Comment by rossberg** [comment]
@binji, yes, that would make more sense then.

One problem I noticed with that scheme, though, is that it does not provide an obvious name for the tail call instruction on funcrefs -- `ref.func.return_call`? That doesn't seem great.

**Comment by rossberg** [comment]
Abandoning this idea.
