### ISSUE TITLE
Should the baseline proposal include ref.func?

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/reference-types#4]
The proposal currently allows getting and setting elements from anyfunc tables, but provides no way of producing such values separately, which is a weird functionality gap.

We could already add the instruction `ref.func $f` for creating a reference to a given function `$f`, which is currently mentioned in the function reference extension only. One caveat is that in the baseline type system we cannot yet provide it with its ideal type, we can only support
```
ref.func $f : [] -> [anyfunc]
```
However, thanks to subtyping, it would be a backwards-compatible change to refine that typing rule to return the more specific type `(ref <functype-of-$f>)` in later versions. So it seems save to add it now with weaker typing.

**Comment by lars-t-hansen** [comment]
We've implemented it; it seems to be in the spec and the interpreter and overview; seems like a done deal?

**Comment by rossberg** [comment]
Done.
