### ISSUE TITLE
Adding modified JS spec in the README.

### ISSUE THREAD

**Issue by kmiller68** [WebAssembly/reference-types#44]
As far as I can tell, there is no link to a formatted copy of the modified JS API. Would it be possible to add this to the README?

**Comment by rossberg** [comment]
Okay, after spending half a day trying to get Bikeshed to work on my new laptop I gave up. The Python troubles wouldn't end.

Ideally, we should have the same auto-deployment on these forks as we have for the spec repo. But my GH fu wasn't good enough to set this up. I tried mirroring all the settings from the spec repo, but no effect. Does anybody have an exact recipe how to do this? (GH docs weren't all that helpful.)

**Comment by binji** [comment]
I'll take a look

**Comment by binji** [comment]
It seems we use the guide described here: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd. There's a simpler way using travis directly here: https://docs.travis-ci.com/user/deployment/pages/

We should probably switch to it at some point. For now, I'm testing a different deploy_key for this repo (they can't be shared) to see if it will work. I've also copied the webhooks from the spec repo, and enabled this repo in `travis-ci.org`. There are a lot of steps here, we should add this to the [new proposals checklist](https://github.com/WebAssembly/proposals/issues/40).

**Comment by binji** [comment]
Seemed to work: https://webassembly.github.io/reference-types/

**Comment by rossberg** [comment]
Fantastic, thanks @binji! I'll try to update my other repos as well.
