### ISSUE TITLE
[js-api] ToWebAssemblyValue signature change

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/reference-types#51]
In #8, ToWebAssemblyValue gained an additional _error_ argument; the current spec only passes it in a single call site. It seems like it had a caller that passed `LinkError` at the time. Presumably all callers should pass a value here; otherwise the argument should be marked as optional.

Alternatively, the algorithm should always throw a `TypeError`; that's what it already throws when `ToInt32` and friends fail.

**Comment by ioannad** [comment]
I also think that the 3rd (error) argument of `ToWebAssemblyValue` can be safely removed, since there is no `LinkError` to propagate anymore. If such an error propagation is needed in the future, I would also go for an optional third argument.
