### ISSUE TITLE
Should WebAssembly support anyref globals?

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/reference-types#6]
Intuitively I understood anyref as a new value type. Therefore I expected anyref to be allowed in signatures,  locals, and globals. The current proposal does not mention globals though. I wonder if we should support anyref globals, just for symmetry to the other value types.

**Comment by rossberg** [comment]
As you say, it's just a new value type, so that implicitly makes it available for globals, too.

**Comment by gahaas** [comment]
Ah, okay, I did not see any tests for this case and wondered if globals are actually intended.

Are the only ways to initialize an anyref global to use `anyref.null`, or the index of another global?

**Comment by rossberg** [comment]
Yes, see the modified definition of constant expression.

I should probably add a test for globals then.

**Comment by gahaas** [comment]
Ah, okay, thanks!
