### ISSUE TITLE
Reference types for phase 4?

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/reference-types#61]
After going through the open issues, there appear to be two substantive core language issues (#55, #60), both of which can probably be postponed if we want to or if we can't find agreement quickly.  There is one corner case (#40) that should probably be resolved in favor of current behavior, because sentiment in the discussion is tilting in that direction.  The JS API also has a small number of mop-up issues that may or may not already be done (#9, #20, #22, #51); investigating.  The remaining open issues are discussion items or feature requests that have been postponed.

The process document requires these for phase 4 (with my comments about status):

* Two or more Web VMs implement the feature.
  * Firefox is tracking the spec, as is Chrome, I believe.  @mstarzinger?
* At least one toolchain implements the feature.
  * Don't know what the status is here. @alexcrichton @kripken @sbc100, comments?
* The formalization and the reference interpreter are usually updated
  * These seem fine to me, @rossberg do you believe we're complete, modulo issues listed above?
* Community Group has reached consensus in support of the feature.
  * We have to have a poll to gauge this

We may need to ship [bulk memory](https://github.com/WebAssembly/bulk-memory-operations) at the same time, as the two proposals touch in various ways, but if anything that proposal is even closer to a shipping state.

**Comment by rossberg** [comment]
I'm afraid #31 is still open in terms of incorporating it into the proposal, see my latest comment there.

**Comment by gahaas** [comment]
Chrome/V8 is passing all spec tests at the moment.

**Comment by alexcrichton** [comment]
> At least one toolchain implements the feature. 

The Rust and WebAssembly toolchain, specifically `wasm-bindgen`, does have support for reference types. There is not native support in the Rust compiler itself (nor LLVM, although that is [being worked on](https://reviews.llvm.org/D66035)). The support in `wasm-bindgen` is definitely "MVP status" where it doesn't really exercise a huge amount of features of the reference types proposal, largely just growing tables and get/set in tables.

That being said though it is well tested (against Node) and should be ready to ship and/or promote to a stable feature of the toolchain! A lot of the surrounding tooling has support for it too such as `wabt`, Rust toolchain crates, etc.

**Comment by sbc100** [comment]
I'm hoping to land the final PRs in `wabt` to allow it to pass all the current spec tests today.

**Comment by aheejin** [comment]
I’m working on Binaryen support.

**Comment by tlively** [comment]
Binaryen support alone is enough to get AssemblyScript working, but I'm not sure what their roadmap is for supporting reference types. cc @dcodeIO who can supply more AssemblyScript information.

**Comment by dcodeIO** [comment]
AssemblyScript supports the [opaque anyref type](https://github.com/WebAssembly/binaryen/pull/2294) as implemented in Binaryen, that is one can declare variables and function parameters of type `anyref` and pass these around. Limitations are that one can't currently store anyrefs in non-imported globals because we are missing a way to initialize them (thinking `ref.null`) before these are set for the first time, and there is no table support yet. Expectation is that we are overly thrilled to follow close as soon as the respective bits land in Binaryen :)

**Comment by rossberg** [comment]
I rebased this proposal on the bulk proposal and filled the gaps between the two. Also implemented declarative element segments (#31) and addressed remaining todos in core spec and interpreter.

Remaining technical tasks:

* A couple of minor adjustments to the JS API spec (#22, #51, #67).
* Test generation for bulk instructions over multiple tables (#74).

Other than that, the main open issue is #69, which is recent and awaiting more feedback from @lukewagner.

**Comment by aheejin** [comment]
Toolchain support is not complete yet. Emscripten (including LLVM + Binaryen) has a partial support:
- LLVM: Does not have support yet, but no frontend languages generate reference types for now
- Binaryen: Has a partial support but lacks table instruction support for now. I don't think it takes too much time to add them, but I'm not sure it is gonna be done before the Feb CG meeting. Also needs to implement #73.

**Comment by eqrion** [comment]
The two major issues blocking this, #69 and #76, are now resolved. Spidermonkey has updated our implementation for the latest changes. At least one toolchain, wasm-bindgen, implements the spec and is up to date with the latest changes. I believe the reference interpreter is up to date with all agreed upon changes.

Are there any other issues that should block us from moving this feature to phase 4 now?

I see webassembly/design#1343 mentioned an impact on this proposal, but appears to have reached a conclusion that it doesn't need to block this proposal. Is that accurate @rosstate?

**Comment by RossTate** [comment]
Yep!

**Comment by rossberg** [comment]
I created a [PR](https://github.com/WebAssembly/meetings/pull/565) to add it tomorrow's agenda.

**Comment by dcodeIO** [comment]
As of https://github.com/WebAssembly/reference-types/issues/69 implemented in https://github.com/WebAssembly/reference-types/pull/87 I'd like to add that the last minute removal of anyref (subtyping) might lead to interoperability concerns with JS.

While I understand that there are technical aspects leading to the decision, it seems that the change fundamentally limits how Wasm and JS can interoperate in the broader ecosystem which seems much more important than implementation details, i.e. an `anyref` value that is not known to be either an object or a function might not be very useful in Wasm, but it certainly is in JS, and a JS module might want to pass any JS value *through* a WebAssembly module, or the WebAssembly module might want to hold on to it to call a JS API (let's say indirectly using it as a `Map` key or whatnot), and that value might be an object or a function.

As such I suggest to evaluate if this is objectively reasonable before going to phase 4.

**Comment by dcodeIO** [comment]
Sorry for the noise. While writing my last comment I figured that just `externref` with no subtyping is probably good enough. Misunderstand something in a prior discussion.

**Comment by binji** [comment]
:tada: Reference types advanced to phase 4 in the [June 23rd CG meeting](https://github.com/WebAssembly/meetings/blob/master/main/2020/CG-06-23.md#poll-on-advancing-to-phase-4)! :tada:
