### ISSUE TITLE
Compacting/reusing anyref table indices to prevent fragmentation

### ISSUE THREAD

**Issue by jayphelps** [WebAssembly/reference-types#62]
I'm implementing a language runtime that mixes linear memory allocated code with anyref's that need to persist in a "heap", in the case of Wasm that means stored in a table `(table 1 anyref)`. In case readers aren't familiar, linear memory cannot directly store anyrefs, but you can store it in a table at a particular index, then store that index in linear memory.

The tricky part is when you want to reuse old, now unused, indices so you're not growing the table size indefinitely. When that table index is "freed" by removing the anyref from that particular index, the anyref itself can potentially be GC'd (if nothing else has a reference to it) but you need some way of knowing that index can be reused now.

I couldn't find any discussions around this (apologies if I missed them!) so I'm curious what folks think the ideal approach is for handling this? The most obvious might be some sort of mark-compact like thing, but it's not clear how one would update the table indices stored in linear memory. Seems like you'd almost have to have another indirection; two linear memory dictionaries of `[table_index]: pointer` and `[pointer]: table_index` so you can change what table index your fake "pointer" points to.

Another solution might be keeping a linear memory vector of freed indices that have been reclaimed, using up those first before appending to the end of the table or resizing.

**Comment by lukewagner** [comment]
In the short term, I would use the free-list-in-linear-memory approach.  In the longer-term, a cute optimization would be to store the free list inline, using `i31ref` :)

**Comment by rossberg** [comment]
I think this has been answered, closing.
