### ISSUE TITLE
Rename ref.is_null to ref.eq_null

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/reference-types#7]
The instruction seems quite similar to the i32.eqz instruction, so I think ref.eq_null would be more consistent than ref.is_null.

**Comment by rossberg** [comment]
I did not use "eq" in this case to avoid confusion over the fact that this instruction can be used even on types that are not `eqref`. However, regarding consistent naming conventions, it should probably be named `ref.isnull`.

**Comment by lars-t-hansen** [comment]
I don't understand why "isnull" is more consistent naming, there is equally good precedent for "is_null", considering "call_indirect", "get_local", and others.

**Comment by rossberg** [comment]
@lars-t-hansen, it's a minor thing, but I was comparing it to similar ones like `eqz`. Plus, so far, we have mainly been using underscore to group parts of the mnemonic that represent some kind of concept that is reappearing in a whole group of operators. Not a very strong reason, though.
