### ISSUE TITLE
table.fill tests should match new bounds check semantics from bulk-memory proposal

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/reference-types#70]
Since this change to bulk memory bounds checks are now performed before fill operations:
 https://github.com/WebAssembly/bulk-memory-operations/pull/123

However table_fill.wast still includes tests that depend on partial execution of the fill.

**Comment by sbc100** [comment]
With this change I don't think its possible for an implementation to pass both reference-types and bulk-memory tests at the same time.

**Comment by rossberg** [comment]
I just looked into this, but AFAICT, it was already up to date, and all the tests in table_fill.wast look fine. Can you point me to which test specifically you think is wrong?

**Comment by rossberg** [comment]
Ah, sorry, I think that was fixed recently by my rebase on the bulk proposal. Should be fine now.

**Comment by sbc100** [comment]
Thanks!
