### ISSUE TITLE
select and br_table spec tests are inconsistent

### ISSUE THREAD

**Issue by ecmziegler** [WebAssembly/reference-types#75]
The latest spec tests seem to produce invalid JS code, e.g. in `select.wast`
https://github.com/WebAssembly/reference-types/blob/2719ec316ca1c31527d8d0a64a258f18e706d84d/test/core/select.wast#L285
https://github.com/WebAssembly/reference-types/blob/2719ec316ca1c31527d8d0a64a258f18e706d84d/test/core/select.wast#L288
The `ref.func` is unknown by JS (`ReferenceError: ref is not defined`) and therefore produces an error. Instead, the result should be compared to the `$dummy` function reference which needs to be made accessible.

Similarly in `br_table.wast`:
https://github.com/WebAssembly/reference-types/blob/2719ec316ca1c31527d8d0a64a258f18e706d84d/test/core/br_table.wast#L1499-L1510

Also, the `join-funcref` test should maybe be using `anyref` as type instead of `funcref`:
https://github.com/WebAssembly/reference-types/blob/2719ec316ca1c31527d8d0a64a258f18e706d84d/test/core/select.wast#L45-L51

**Comment by rossberg** [comment]
Indeed, I screwed that up when rebasing the branch. Should be fixed by #78, PTAL (unfortunately, GH didn't allow me to enter you as a reviewer).

**Comment by ecmziegler** [comment]
👍 thanks!
