### ISSUE TITLE
Binary encoding for `table.init` spec doesn't match implementations

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/reference-types#81]
The [online specification](https://webassembly.github.io/reference-types/core/binary/instructions.html#table-instructions) indicates that the table segment is encoded first and the element segment is encoded second, but this doesn't agree with other implementations, for example:

* [Gecko reads the segment index first](https://github.com/mozilla/gecko-dev/blob/8435dfb4fb892e695d450143094a21503f6405b6/js/src/wasm/WasmOpIter.h#L2438-L2445) which I think also means that the encoding of `memory.init` doesn't match the specification as well (?)
* [wabt](https://github.com/WebAssembly/wabt/blob/94ad3e84817c546b1313e161da565d181b1a470c/src/binary-reader.cc#L1447-L1458) reads the element segment first, then the table index
* [v8](https://github.com/v8/v8/blob/4f28e6d9a162429cee5ea730fbff449a5df0287f/src/wasm/function-body-decoder-impl.h#L550-L556) I think also reads the element segment before the table index.

Is this a bug in the specification? Or do engines need to update which one they're reading first?

**Comment by rossberg** [comment]
Indeed, mixed up the binary order for *.init (it's a bit irregular). See #82.
