### ISSUE TITLE
Relation between externref and anyref

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/reference-types#91]
What ist the relation between the `externref` and `anyref` type. In the [overview](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) both are used. I have  thought `anyref` was renamed to `externref`. But now both terms are in the overview. I am confused.

**Comment by binji** [comment]
It looks like `anyref` is only used in the "Possible Future Extensions" section. In particular, `anyref` is defined [here](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md#subtyping):

```
t <: anyref for all reftypes t
```

Which means that `anyref` is a super type of all reference types.

OTOH, `externref` can only represent host references. From the overview:

> allow host references to be represented directly by type `externref`

**Comment by rossberg** [comment]
What @binji said. IOW, externref is a different type that will be a subtype of anyref once the latter is introduced.

**Comment by Horcrux7** [comment]
This means I must change anyref to externref now and later I change it back because I need a type for JS and GC objects. Sounds very chaotic.

I expect then that exnref can not be saved in an externref.

**Comment by rossberg** [comment]
Not everybody is happy with this outcome, but the CG couldn't agree on anything else.

FYI, some folks have argued that exnref should not even be a subtype of anyref. If this is relevant to you, you may want to speak up and describe your use case, e.g. on the EH proposal.

**Comment by Horcrux7** [comment]
> Not everybody is happy with this outcome, but the CG couldn't agree on anything else.

I know there was an endless discussion. I have read it partly because the information content was very small.

> If this is relevant to you, you may want to speak up and describe your use case, e.g. on the EH proposal.

No strong requirement. It is always possible to use boxing to convert any object into a GC type. Can be that some things will be simpler. It required only a new thinking. That requires understanding the new structure of WASM.

**Comment by rossberg** [comment]
I believe this has been answered.
