### ISSUE TITLE
Type of ref.func instruction

### ISSUE THREAD

**Issue by titzer** [WebAssembly/reference-types#97]
The currently stated type of the ref.func instruction is [] -> [funcref]. I assume that with the typed functions proposal, this return type will be refined to be the actual type of the function referenced in the immediate. Is it worth mentioning this in the overview? I can't see a case where this proposal isn't future-proof, but it might be good to state it here to double-check our understanding.

**Comment by rossberg** [comment]
Yes, see the description of `ref.func` in [this section](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md#language-extensions) of the Overviews. ;) See also the refinement [in the func-ref proposal](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md#functions).

**Comment by rossberg** [comment]
I believe there is no action to be taken.
